apiVersion: apps/v1
kind: Deployment
metadata:
  name: harifarms-app
  namespace: harifarms
spec:
  replicas: 3
  selector:
    matchLabels:
      app: harifarms-app
  template:
    metadata:
      labels:
        app: harifarms-app
    spec:
      containers:
        - name: harifarms-app
          image: harifarms:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: postgres-secret
          env:
            - name: SPRING_CONFIG_LOCATION
              value: /config/application.properties
            - name: JAVA_OPTS
              value: "-Xms512m -Xmx1024m"
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: harifarms-config