apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: harifarms-role
  namespace: harifarms
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list", "watch"]